#!/usr/bin/env bash

export TEMPLATE_ELASTIC_VERSION="7.9.3"
export TEMPLATE_SUPPORT_DIAGNOSTICS_VERSION="7.1.5"
export TEMPLATE_ELASTICSEARCH_OPENJDK_VERSION="13.0.2"
export TEMPLATE_ELASTICSEARCH_PROMETHEUS_EXPORTER_VERSION="1.1.0"
