#!/usr/bin/env bash

export TEMPLATE_ELASTIC_VERSION="7.3.2"
export TEMPLATE_SUPPORT_DIAGNOSTICS_VERSION="7.0.9"
export TEMPLATE_ELASTICSEARCH_OPENJDK_VERSION="11.0.2"
export TEMPLATE_ELASTICSEARCH_PROMETHEUS_EXPORTER_VERSION="1.1.0"
export TEMPLATE_SEARCHGUARD_ELASTIC_VERSION="7-${TEMPLATE_ELASTIC_VERSION}-37.0.0"
export TEMPLATE_SEARCHGUARD_KIBANA_PLUGIN_VERSION="${TEMPLATE_ELASTIC_VERSION}-36.0.0"